##
# Informal Systems Audit Report
#
# @file
# @version 0.1

# NOTE: Run `make init` to initialize the report skeleton

ifeq (${AUDITS_HOME},)
$(error AUDITS_HOME must be set.)
else
include ${AUDITS_HOME}/guide/reports/Makefile
endif

# end
